version?: ?'3' 
services?:
   machine1?:
        image?: ?busybox 
        environment?:
        - MACHINE=1 
        entrypoint?: ?sleep 5d
machine2?:
        image?: ?busybox 
        environment?:
        - MACHINE=2 
        entrypoint?: ?sleep 5d
machine3?: 
        image?: ?busybox 
        environment?:
        - MACHINE=2 
        entrypoint?: ?sleep 5d