version: '2' 
networks:
  app-network:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
  myapplication:
    image: 'counter-services'
    networks:
      - app-tier